"""
JARVIS ULTIMATE - ROBUST EDITION
"""

import os
import sys
import time
import subprocess
import speech_recognition as sr
import pyttsx3
import webbrowser
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

# CONFIGURATION
# ------------------------------------------------------------------
API_KEY = os.getenv("OPENAI_API_KEY")
WAKE_WORD = "jarvis"

client = OpenAI(
    api_key=API_KEY,
    base_url="https://openrouter.ai/api/v1"
)
MODEL_NAME = "openai/gpt-3.5-turbo"

engine = pyttsx3.init()
engine.setProperty('rate', 165)

def speak(text):
    print(f"\n[JARVIS]: {text}")
    try:
        engine.say(text)
        engine.runAndWait()
    except:
        pass

def listen():
    recognizer = sr.Recognizer()
    
    # Sensitivity settings for Windows
    recognizer.energy_threshold = 300  # Lower = more sensitive
    recognizer.dynamic_energy_threshold = True
    recognizer.pause_threshold = 0.8   # Wait shorter time for pauses
    
    try:
        with sr.Microphone() as source:
            print("\n[  MIC ACTIVE  ] Listening... (Speak now)")
            recognizer.adjust_for_ambient_noise(source, duration=1.0) # Calibrate
            
            try:
                # Increased timeout
                audio = recognizer.listen(source, timeout=5, phrase_time_limit=10)
                print("[  PROCESSING  ] Recognizing speech...")
                text = recognizer.recognize_google(audio).lower()
                print(f"[  HEARD       ] '{text}'")
                return text
            except sr.WaitTimeoutError:
                print("[  TIMEOUT     ] No speech detected.")
                return ""
            except sr.UnknownValueError:
                print("[  UNKNOWN     ] Audio detected but not understood.")
                return ""
    except Exception as e:
        print(f"[  MIC ERROR   ] {e}")
        # If mic crashes, ask for text input as fallback
        return input("Mic failed. Type command here: ").lower()

def execute_generated_code(code):
    """Run Python code generated by AI and Capture Output"""
    speak("Executing task...")
    
    # Save code to file
    filename = "task_exec.py"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(code)
    
    print("--- CODE GENERATED ---")
    print(code)
    print("----------------------")

    try:
        # Execute and capture output (Timeout 30s)
        result = subprocess.run(
            [sys.executable, filename], 
            capture_output=True, 
            text=True, 
            timeout=30
        )
        
        # Check for errors
        if result.returncode != 0:
            error_msg = result.stderr
            print(f"Execution Error: {error_msg}")
            speak("I tried to execute the task, but there was an error.")
            if len(error_msg) < 100:
                speak(f"The error was: {error_msg}")
        else:
            output = result.stdout
            print(f"Output: {output}")
            speak("Task completed successfully.")
            if output:
                speak(f"Output: {output}")

    except Exception as e:
        speak(f"System execution failed: {e}")

def process_complex_task(command):
    """Processing Logic"""
    speak("One moment...")
    
    system_prompt = """
    You are JARVIS.
    The user wants you to perform a task on their computer.
    
    INSTRUCTIONS:
    1. WRITE PYTHON CODE to do exactly what the user asked.
    2. START code with ```python and END with ```.
    3. IMPORT all necessary libraries (os, sys, etc).
    4. If creating a file (HTML, txt), write the python code to open() and write() that file.
    5. Do NOT just explain. WRITE THE CODE.
    """
    
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": command}
            ]
        )
        content = response.choices[0].message.content
        
        # Extract Code
        if "```python" in content:
            code = content.split("```python")[1].split("```")[0].strip()
            execute_generated_code(code)
        elif "```" in content: # Fallback
            code = content.split("```")[1].split("```")[0].strip()
            execute_generated_code(code)
        else:
            # No code found, just speak the response
            speak(content)
            
    except Exception as e:
        speak("I am having trouble connecting to the internet.")
        print(f"API Error: {e}")

def main():
    speak("Fixed System Online. Ready for tasks.")
    
    while True:
        text = listen()
        if not text:
            continue
            
        if not text:
            continue
            
        # DIRECT CONTROL - NO WAKE WORD NEEDED
        command = text.strip()
        print(f"[  COMMAND     ] Processing: '{command}'")

        if command.startswith("open "):
            app = command.replace("open ", "").strip()
            speak(f"Opening {app}")
            # Simple OS Start
            try:
                os.system(f"start {app}") 
            except:
                speak(f"Could not open {app}")
        
        elif "github" in command or ("save" in command and "this" in command):
            try:
                from github_manager import create_private_repo, push_to_github
                speak("Setting up your private GitHub repository.")
                repo_name = "jarvis-project-backup"
                repo_url = create_private_repo(repo_name)
                if repo_url:
                    speak(f"Repository {repo_name} is ready. Pushing files now.")
                    if push_to_github(repo_url):
                        speak("Project successfully saved to your private GitHub repository.")
                    else:
                        speak("I encountered an error pushing the files. Check the console for details.")
                else:
                    speak("I couldn't create the repository. Did you add your GITHUB_TOKEN to the .env file?")
            except Exception as e:
                speak(f"GitHub operation failed: {e}")
            
        # Complex Tasks (AI)
        else:
            process_complex_task(command)

if __name__ == "__main__":
    main()
